/*
 * generated by Xtext 2.25.0
 */
package org.lama.javaLaMa.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.lama.javaLaMa.LaMaDSLRuntimeModule;
import org.lama.javaLaMa.LaMaDSLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LaMaDSLIdeSetup extends LaMaDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LaMaDSLRuntimeModule(), new LaMaDSLIdeModule()));
	}
	
}
