/*
 * generated by Xtext 2.25.0
 */
package org.lama.javaLaMa.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LaMaDSLUiModule extends AbstractLaMaDSLUiModule {

	public LaMaDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
