/*
 * generated by Xtext 2.25.0
 */
package org.lama.javaLaMa;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LaMaDSLStandaloneSetup extends LaMaDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new LaMaDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
